version: "3"

services:

  prom:
    image: prom/prometheus:v2.4.3
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./prometheus/alertrules.yml:/etc/prometheus/alertrules.yml
    command: 
     - "--config.file=/etc/prometheus/prometheus.yml"
     - "--storage.tsdb.path=/prometheus"
     - "--web.enable-lifecycle"
    ports:
     - 9090:9090
     
  grafana:
    image: grafana/grafana:5.2.4
    ports:
     - 3000:3000
    env_file:
      - ./grafana/config.monitoring
    depends_on:
      - prom
      
  alertmanager:
    image: prom/alertmanager:v0.19.0
    volumes:
     - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
     - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
     - 9093:9093