management:
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.95D, 0.99D
      sla:
        http.server.requests: 1ms,5ms
