server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5D, 0.9D, 0.95D, 0.99D
      sla:
        http.server.requests: 20ms,40ms
  server:
    port: 8090

